# Generated by Django 5.2.8 on 2025-11-09 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='Уровень сети')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Обязательное поле. Уникальное название предприятия', max_length=150, unique=True, verbose_name='Название предприятия')),
                ('email', models.EmailField(help_text='Адрес электронной почты', max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=150, verbose_name='Номер дома')),
                ('product', models.CharField(max_length=200, verbose_name='Название продукции')),
                ('product_model', models.CharField(max_length=100, verbose_name='Модель продукта')),
                ('product_release_date', models.DateField(verbose_name='Дата выхода продукта')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.networknode')),
            ],
            options={
                'verbose_name': 'Объект сети',
                'verbose_name_plural': 'Объекты сети',
            },
        ),
    ]
