# Generated by Django 5.2.8 on 2025-11-09 08:32

import network.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[network.validators.validate_debt]),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='product_release_date',
            field=models.DateField(validators=[network.validators.validate_product_release_date], verbose_name='Дата выхода продукта'),
        ),
    ]
